<?php
/**
 * @package: 
 * @author: Oleg Pryadko (oleg@websitezen.com)
 * @createdon: 6/20/15
 * @license: GPL v.3 or later
 */
require_once dirname(__FILE__).'/mailchimp/Mailchimp.class.php';


class MailchimpX extends Mailchimp {
    /** @var modX A reference to the modX object. */
    public $modx = null;
    public function __construct(modX &$modx, $apikey = null, $opts = array()) {
        $this->modx =& $modx;
        parent::__construct($apikey, $opts); // TODO: Change the autogenerated stub
    }

    public function getHumanErrorType(Exception $e) {
        $class_name = get_class($e);
        $error_type = str_replace('_', ' ', preg_replace('/([\w_])([A-Z])/', '$1 $2', $class_name));
        return $error_type;
    }

}
